name: CI
on:
  push:
    branches:
      - master

jobs:
  vue:
    name: vue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # react项目为npm run-script build，vue项目改为npm run build
      - name: Install and Build      
        run: |
          npm install node-gyp
          npm install
          npm run build
     
      # react项目的FOLDER为build，vue项目改为dist   
      - name: Deploy Github
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

  gitee:
    needs: vue
    name: Mirror to gitee Repo
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: "git@github.com:miku-o/index.git"
          destination-repo: "git@gitee.com:miku-o/index.git"